### ISSUE TITLE
Initial setting: Flask Sign up & Sign in

### ISSUE THREAD

**Issue by heewoneha** [troymerai/COSMIC-tryon#1]
## Todo

- [x] 초기 세팅: Flask 회원가입 & 로그인
- [x] Connect with Azure MySQL Database (Azure for Student 1년 무료)
- [x] Postman local test
