### ISSUE TITLE
feat: ipynb 코드를 Flask API에 넣기

### ISSUE THREAD

**Issue by heewoneha** [troymerai/COSMIC-tryon#10]
#3 참고

### Todo
- [x] 모델 관련 DB 테이블 만들기 및 Foreign Key 설정
- [x] venv에 관련 모듈 설치 및 `Backend/requirements.txt`에 반영
- [x] 전반적으로 기존 구조 개선 (Notion ERD 참고)
- [x] 모델 API 테스트
