### ISSUE TITLE
Refactor: Sign up & Sign in 공통 코드, 모델 코드 분리

### ISSUE THREAD

**Issue by heewoneha** [troymerai/COSMIC-tryon#4]
### Todo

- [x] 공통 코드 `common.py`로 분리
- [x] 모델 코드 (User class 등) `model/~.py`로 분리
- [x] 각 테이블에 `created_at` column 추가 (한국 시간으로 TIMESTAMP 저장)
